language: node_js
node_js:
- '11.0'
branches:
  only:
  - master
before-script:
- npm install -g firebase-tools
script:
- npm install
- npm run build
- firebase deploy --only hosting --project portfolio-ec01a --non-interactive --token=$FIREBASE_TOKEN
  -m "Github deploy"
env:
  global:
    secure: n84iDBUCLZDIiuqR79tCL4T9lllMz84cSnsyuP7AjbxppLl11DnU0oF1lbEwvUKFQ3VtkYut6yMvQsWv3p23cl/r4kNHN0I+/inh/tOSKmwtcysk9oMxSiaYRfc4eb2AWV+xH5VPdBAAjL+Dp1UX8fONMdFFaQznQkINzbT6nTor/O0n4K8HgdeQbYFMZJuhRZr6RFfLJHoyJGz50JrkLjgzUpJO4cTsL2EPltRHE+m6g64TEGyoqnMMOwoadLPylAU8qTunpKGcxdOYzeO+c6zmDPNHNK8YokeQZZC6M0mYQy9+hPVNfHCW+mWOeFybISTlhi01jNAvgkBIxMG9+hZKILDeCbCaODDDZbIKL7QCmWQY+SW7EwjIKTw5YFkE8JA19epsSKsgWpkmV2rZ39/jxkkDQUX46oWpM77q1WiTwflGp30Jbx+gZlpB5ivIFXjgslmLaqiF6MdNnMe0VBZ7Wc+YHD5uU77zW8rZuSQEakkDR6yw59nn3RhQgCtm2tvyezxTrL/W73m64eFSrxO2bKw4+enWN+7fEzMdqzHRnjCw4LCShgmDklfPYhSh0WC9Jp9s7PWi2VHY/e4htGOy0uSCqQlTz4yJNo0K/vR/6ptg0QSh1rOQm5pNpk/2JpuJHi20W5WCfWHywMpv3Thz5Wzibd5s9fSQcc3zAA8=
